# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: user_timeline
email: bytelmen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    user timeline of twitter for Chinese access
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
timezone: Asia/Shanghai

# Build settings
markdown: kramdown
gems :
  - jekyll-paginate
paginate: 5
paginate_path: "/post/page:num"
